Repository Nexters/BlockBuilderFront, pull requests merged in 2025-02, with the labels that each got.

#9 feature: 검색바 추가 및 챗봇 화면 UI 수정
  src/app/chat/components/LevelCard/LevelCard.tsx
  src/app/chat/components/QuestionRecommendation/QuestionRecommendation.tsx
  src/app/chat/components/QuestionRecommendation/index.ts
  src/app/chat/components/Questions/NavigationButton.tsx
  src/app/chat/components/Questions/Question.tsx
  src/app/chat/components/Questions/Questions.tsx
  src/app/chat/components/SearchBar/SearchBar.tsx
  src/app/chat/components/SearchBar/index.ts
  src/app/chat/page.tsx
  src/assets/icons/ArrowRight.tsx
  src/assets/icons/index.tsx
  src/components/common/ResponsiveContainer/Desktop.tsx
Labels: feature, 🟡 바나나

#10 feat: 소식 - 이벤트 섹션 초안
  .prettierrc
  .prettierrc.mjs
  package.json
  public/icons/information.svg
  public/images/blockchainSymbol/aptos.webp
  public/images/blockchainSymbol/arbitrum.webp
  public/images/blockchainSymbol/avalanche.webp
  public/images/blockchainSymbol/cosmos.webp
  public/images/blockchainSymbol/etc.webp
  public/images/blockchainSymbol/ethereum.webp
  public/images/blockchainSymbol/mina.webp
  public/images/blockchainSymbol/near.webp
  public/images/blockchainSymbol/optimism.webp
  public/images/blockchainSymbol/solana.webp
  public/images/blockchainSymbol/sui.webp
  src/app/information/components/BlockchainEventSection/BlockchainEventList.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventSection.tsx
  src/app/information/components/BlockchainLabel/BlockchainLabel.tsx
  src/app/information/components/BlockchainLabel/const.ts
  src/app/information/components/BlockchainNewsSection/BlockchainNewsSection.tsx
  src/app/information/const.ts
  src/app/information/page.tsx
  src/assets/icons/Information.tsx
  src/assets/icons/index.tsx
  src/components/common/ResponsiveContainer/Desktop.tsx
  src/components/common/ResponsiveContainer/Tablet.tsx
  src/hooks/useNavigation.tsx
  src/utils/date.ts
  tailwind.config.js
Labels: 🔴 빅터, feature

#5 feat: 소식 - 최신 뉴스 탭 초안
  .prettierrc
  .prettierrc.mjs
  package-lock.json
  package.json
  public/icons/information.svg
  public/images/blockchainSymbol/aptos.webp
  public/images/blockchainSymbol/arbitrum.webp
  public/images/blockchainSymbol/avalanche.webp
  public/images/blockchainSymbol/cosmos.webp
  public/images/blockchainSymbol/etc.webp
  public/images/blockchainSymbol/ethereum.webp
  public/images/blockchainSymbol/mina.webp
  public/images/blockchainSymbol/near.webp
  public/images/blockchainSymbol/optimism.webp
  public/images/blockchainSymbol/solana.webp
  public/images/blockchainSymbol/sui.webp
  public/images/no-result.webp
  src/app/globals.css
  src/app/information/components/BlockchainEventSection/BlockchainEventList.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventSection.tsx
  src/app/information/components/BlockchainLabel/BlockchainLabel.tsx
  src/app/information/components/BlockchainLabel/const.ts
  src/app/information/components/BlockchainNewsSection/BlockchainNewsSection.tsx
  src/app/information/const.ts
  src/app/information/page.tsx
  src/assets/icons/Information.tsx
  src/assets/icons/index.tsx
  src/components/common/ResponsiveContainer/Desktop.tsx
  src/components/common/ResponsiveContainer/Tablet.tsx
  src/hooks/useNavigation.tsx
  src/utils/date.ts
  tailwind.config.js
Labels: 🔴 빅터, feature

#16 feat: 소식 - 이벤트 섹션 api
  public/icons/bag.svg
  public/icons/meetup.svg
  src/app/information/actions/fetchNewsList.ts
  src/app/information/api/fetchBlockchainInformation.ts
  src/app/information/components/BlockchainEventSection/BlockchainEvent.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventList.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventSection.client.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventSection.server.tsx
  src/app/information/components/BlockchainLabel/BlockchainLabel.tsx
  src/app/information/components/BlockchainLabel/const.ts
  src/app/information/components/BlockchainNewsSection/BlockchainNews.tsx
  src/app/information/components/BlockchainNewsSection/BlockchainNewsSection.client.tsx
  src/app/information/components/BlockchainNewsSection/BlockchainNewsSection.server.tsx
  src/app/information/const.ts
  src/app/information/page.tsx
  src/app/information/type.ts
  src/assets/icons/Bag.tsx
  src/assets/icons/Meetup.tsx
  src/assets/icons/index.tsx
  src/utils/array.ts
Labels: 🔴 빅터, feature

#15 feat: 소식 탭 - 뉴스 섹션 api, infinite scroll
  next.config.ts
  package-lock.json
  package.json
  public/icons/bag.svg
  public/icons/meetup.svg
  src/app/api/[...path]/route.ts
  src/app/information/api/fetchBlockchainInformation.ts
  src/app/information/components/BlockchainEventSection/BlockchainEvent.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventList.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventSection.client.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventSection.server.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventSection.tsx
  src/app/information/components/BlockchainLabel/BlockchainLabel.tsx
  src/app/information/components/BlockchainLabel/const.ts
  src/app/information/components/BlockchainNewsSection/BlockchainNews.tsx
  src/app/information/components/BlockchainNewsSection/BlockchainNewsSection.client.tsx
  src/app/information/components/BlockchainNewsSection/BlockchainNewsSection.server.tsx
  src/app/information/components/BlockchainNewsSection/BlockchainNewsSection.tsx
  src/app/information/const.ts
  src/app/information/page.tsx
  src/app/information/type.ts
  src/assets/icons/Bag.tsx
  src/assets/icons/Meetup.tsx
  src/assets/icons/index.tsx
  src/components/ResponsiveContainer/Tablet.tsx
  src/utils/array.ts
Labels: 🔴 빅터, feature

#19 feat/add ci
  .github/workflows/ci.yml
  src/app/api/[...path]/route.ts
Labels: 🟡 바나나, fix

#17 feat: 투표 - UI
  src/app/poll/components/Container/Container.tsx
  src/app/poll/components/Container/index.ts
  src/app/poll/components/Nickname/Nickname.tsx
  src/app/poll/components/Nickname/index.ts
  src/app/poll/components/Poll/Poll.tsx
  src/app/poll/components/Poll/RadioOption.tsx
  src/app/poll/components/Poll/index.ts
  src/app/poll/components/Tabs/Tabs.tsx
  src/app/poll/components/Tabs/index.ts
  src/app/poll/page.tsx
  src/components/ResponsiveContainer/Tablet.tsx
Labels: 🟢 테디, feature

#24 fix: 공통 스타일
  src/app/globals.css
  src/app/information/components/BlockchainEventSection/BlockchainEventList.tsx
  src/components/ResponsiveContainer/Desktop.tsx
  src/components/ResponsiveContainer/Mobile.tsx
  src/components/ResponsiveContainer/Tablet.tsx
  tailwind.config.js
Labels: 🔴 빅터, fix

#32 fix: 툴팁 z-index 변경 / 투표하기 버튼 로딩 로띠 추가
  src/app/poll/components/Poll/Poll.tsx
  src/app/poll/components/Poll/TooltipContainer.tsx
Labels: 🟢 테디, fix

#33 feat: nft, coin 페이지 로딩 추가
  src/app/chat/components/Questions/Question.tsx
  src/app/coin/page.tsx
  src/app/nft/page.tsx
Labels: feature, 🟡 바나나

#31 QA : 소식 페이지 - 이벤트 섹션
  src/app/information/components/BlockchainEventSection/BlockchainEventList.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventSection.client.tsx
Labels: 🔴 빅터, fix

#34 fix: vercel.json api path 수정
  vercel.json
Labels: 🟡 바나나, fix

#37 feat: Mixpanel 연동 (for. User actions logging)
  package-lock.json
  package.json
  src/app/information/api/fetchBlockchainInformation.ts
  src/app/information/components/BlockchainEventSection/BlockchainEvent.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventList.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEventSection.client.tsx
  src/app/information/components/BlockchainNewsSection/BlockchainNews.tsx
  src/app/information/components/BlockchainNewsSection/BlockchainNewsSection.client.tsx
  src/app/information/hooks/useInformationPageActions.ts
  src/app/information/type.ts
  src/app/layout.tsx
  src/components/Analytics/Analytics.tsx
  src/components/Analytics/mixpanel.ts
  src/hooks/useLogging.ts
Labels: 🔴 빅터, feature

#39 feat: static meta-data draft
  src/app/layout.tsx
  src/app/opengraph-image.png
  src/app/twitter-image.png
Labels: 🔴 빅터, feature

#38 feat: 소식 - Streaming SSR
  src/app/information/page.tsx
Labels: 🔴 빅터, feature

#41 feat: 시작하기, 블록챗 믹스패널 연결 및 기타 버그 수정
  src/app/chat/components/Chat/BotBubble.tsx
  src/app/chat/components/QuestionRecommendation/QuestionRecommendation.tsx
  src/app/chat/components/Questions/NavigationButton.tsx
  src/app/chat/components/Questions/Questions.tsx
  src/app/chat/components/TotalQuestions/TotalQuestions.tsx
  src/app/chat/hooks/useChatPageActions.ts
  src/app/chat/page.tsx
  src/app/coin/hooks/useCoinPageActions.ts
  src/app/coin/page.tsx
  src/app/landing/Card.tsx
  src/app/nft/hooks/useNftPageActions.ts
  src/app/nft/page.tsx
  src/app/quiz/Explanation.tsx
  src/app/quiz/Recommendation.tsx
  src/app/quiz/hooks/useQuizPageActions.ts
  src/app/quiz/page.tsx
  src/components/ResponsiveContainer/Desktop.tsx
  src/components/ResponsiveContainer/Mobile.tsx
  src/hooks/useLandingPageActions.ts
  src/hooks/useScreen.tsx
  src/hooks/useUser.tsx
Labels: 🟡 바나나, fix

#42 feat: 코인 생성 전 입력 폼 페이지 추가
  src/app/coin/page.tsx
  src/app/coin/success/page.tsx
  src/app/coin/useCoin.ts
Labels: 🔴 빅터, feature

#44 feat: 테마 변경 로깅 추가
  src/components/ResponsiveContainer/common/ThemeSwitch.tsx
Labels: 🟢 테디, feature

#45 fix: 코인 로딩 텍스트, 모바일 전체 질문 카테고리 수정
  src/app/chat/components/TotalQuestions/TotalQuestions.tsx
  src/app/coin/success/page.tsx
Labels: 🟡 바나나, fix

#46 fix: 채팅 너비 수정
  src/app/chat/components/Chat/Chat.tsx
Labels: 🟡 바나나, fix

#47 fix: 여백 포함 채팅 너비 설정
  src/app/chat/components/Chat/Chat.tsx
Labels: 🟡 바나나, fix

#49 fix: remove un-used files
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
Labels: 🔴 빅터, fix

#50 refac: 이미지 static blur
  src/app/coin/success/page.tsx
  src/app/information/components/BlockchainEventSection/BlockchainEvent.tsx
  src/app/information/components/BlockchainNewsSection/BlockchainNews.tsx
  src/app/nft/page.tsx
  src/utils/image.ts
Labels: 🔴 빅터, refactoring

#51 fix: initial information's news data
  src/app/information/components/BlockchainNewsSection/BlockchainNewsSection.client.tsx
Labels: 🔴 빅터, fix

#52 fix: remove information's api cache
  src/app/information/api/fetchBlockchainInformation.ts
Labels: 🔴 빅터
