Repository Nexters/BlockBuilderFront, pull requests merged in 2025-01, with the labels that each got.

#1 chore : 스타일링 초기화
  package-lock.json
  package.json
  postcss.config.js
  src/app/globals.css
  src/app/page.module.css
  src/app/page.tsx
  tailwind.config.js
Labels: 🔴 빅터, feature

#2 chore: add github auto-deploy workflow
  .github/workflows/auto-deploy.yml
Labels: feature, 🟡 바나나

#3 다크모드 & 스타일링 에셋 작업
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ThemeSwitch.tsx
  tailwind.config.js
Labels: 🔴 빅터, feature

#6 feat: LNB 추가 및 뷰포트 설정 + 기타 프로젝트 세팅
  .gitignore
  .prettierrc.mjs
  eslint.config.mjs
  package-lock.json
  package.json
  public/icons/chat.svg
  public/icons/dark_mode.svg
  public/icons/light_mode.svg
  public/icons/menu.svg
  public/icons/news.svg
  public/icons/poll.svg
  src/app/layout.tsx
  src/assets/icons/Chat.tsx
  src/assets/icons/DarkMode.tsx
  src/assets/icons/LightMode.tsx
  src/assets/icons/Menu.tsx
  src/assets/icons/News.tsx
  src/assets/icons/Poll.tsx
  src/assets/icons/index.tsx
  src/components/common/ResponsiveContainer/Desktop.tsx
  src/components/common/ResponsiveContainer/Mobile.tsx
  src/components/common/ResponsiveContainer/Tablet.tsx
  src/components/common/ResponsiveContainer/index.tsx
  src/constants/viewport.ts
  src/hooks/useMount.tsx
  src/hooks/useNavigation.tsx
  src/utils/string.ts
  src/utils/viewport.ts
Labels: 🟢 테디, feature

#7 feat: 챗봇 페이지 화면 구현
  package-lock.json
  package.json
  public/images/chat/advanced.png
  public/images/chat/beginner.png
  public/images/chat/intermediate.png
  src/app/chat/components/LevelCard/LevelCard.tsx
  src/app/chat/components/LevelCard/index.ts
  src/app/chat/components/Questions/Question.tsx
  src/app/chat/components/Questions/Questions.tsx
  src/app/chat/components/Questions/index.ts
  src/app/chat/components/Title/Title.tsx
  src/app/chat/components/Title/index.ts
  src/app/chat/data.ts
  src/app/chat/page.tsx
  src/app/globals.css
  tailwind.config.js
Labels: feature, 🟡 바나나

#8 feat: pretendard 폰트 적용
  public/fonts/PretendardVariable.woff2
  src/app/globals.css
  src/app/layout.tsx
Labels: 🟢 테디, feature
